site: StratsCo

url: https://strats.co
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /news/:slug
  games:
    output: true
    permalink: /game/:slug
  redirects:
    output: true
    permalink: /x/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  -
    scope:
      path: ""
      type: "redirects"
    values:
      layout: "redirect"
  

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

paginate: 6
paginate_path: "/news/page:num/"
  